### PR TITLE
Adding Support that hubot is able to send text messages and html messages

### PR DESCRIPTION
**Pull request by argo1984**
…ages for notifications (e.g. OpsGenie, Datadoghq)

### CODE REVIEW

**Comment by davidar** [comment]
These methods don't seem to be part of the hubot Adapter interface?

**Comment by argo1984** [comment]
Hi @davidar,

these methods were not part of the hubot adapter. That is why i added them. The Adapter could only send notices before. In the client sdk for matrix it was defined.

**Comment by patcon** [comment]
Hey @argo1984! I know it's been a long time, but are you still using this adapter, and interested to see this functionality merged?

**Comment by argo1984** [comment]
Hi @patcon, i don't use it anymore. But maybe it helps other users.

**Comment by patcon** [comment]
Thanks for the response, @argo1984!

Sounds like someone else will need to find the time, which is a-ok :) Glad you shared it here, and I hope you're well!

**Pull request closed without merging**
